USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS "Dev Role";

GRANT ROLE "Dev Role" TO USER "AMAN"; -- REPLACE AMAN with your Snowflake USERNAME

ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

GRANT CREATE DATABASE ON ACCOUNT TO ROLE "Dev Role";
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE "Dev Role";

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE "Dev Role";
CREATE DATABASE IF NOT EXISTS Swiggy_Master;

CREATE SCHEMA IF NOT EXISTS Swiggy_Master.Dev;
CREATE SCHEMA IF NOT EXISTS Swiggy_Master.UAT;
CREATE SCHEMA IF NOT EXISTS Swiggy_Master.Prod;

GRANT USAGE ON DATABASE Swiggy_Master TO ROLE "Dev Role";

GRANT USAGE ON SCHEMA Swiggy_Master.Dev TO ROLE "Dev Role";
GRANT USAGE ON SCHEMA Swiggy_Master.UAT TO ROLE "Dev Role";
GRANT USAGE ON SCHEMA Swiggy_Master.Prod TO ROLE "Dev Role";

GRANT CREATE TABLE ON SCHEMA Swiggy_Master.Dev TO ROLE "Dev Role";
GRANT CREATE TABLE ON SCHEMA Swiggy_Master.UAT TO ROLE "Dev Role";
GRANT CREATE TABLE ON SCHEMA Swiggy_Master.Prod TO ROLE "Dev Role";


GRANT USAGE ON DATABASE SWIGGY_MASTER TO ROLE "Dev Role";
GRANT USAGE ON SCHEMA SWIGGY_MASTER.DEV TO ROLE "Dev Role";


GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA SWIGGY_MASTER.DEV TO ROLE "Dev Role";

CREATE DATABASE STREAMLIT_APPS;


GRANT USAGE ON DATABASE STREAMLIT_APPS TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA STREAMLIT_APPS.PUBLIC TO ROLE PUBLIC;
GRANT CREATE STREAMLIT ON SCHEMA STREAMLIT_APPS.PUBLIC TO ROLE PUBLIC;
GRANT CREATE STAGE ON SCHEMA STREAMLIT_APPS.PUBLIC TO ROLE PUBLIC;


CREATE COMPUTE POOL STREAMLIT_COMPUTE_POOL
  MIN_NODES = 1
  MAX_NODES = 3
  INSTANCE_FAMILY = CPU_X64_XS;


GRANT USAGE ON COMPUTE POOL STREAMLIT_COMPUTE_POOL TO ROLE PUBLIC;


CREATE WAREHOUSE STREAMLIT_WAREHOUSE WITH WAREHOUSE_SIZE = XSMALL;


GRANT USAGE ON WAREHOUSE STREAMLIT_WAREHOUSE TO ROLE PUBLIC;


GRANT CREATE STAGE ON SCHEMA SWIGGY_MASTER.DEV TO ROLE "Dev Role";
GRANT CREATE PROCEDURE ON SCHEMA SWIGGY_MASTER.DEV TO ROLE "Dev Role";

